postgres:
  name: postgres
  port: 5432
  targetPort: 5432
  db: postgres
  user: postgres
  password: n?xPtz)MQh^.88^r

redis:
  name: redis
  port: 6379
  targetPort: 6379

redash:
  name: redash
  image: redash/redash:6.0.0.b8537
  envFrom:
  - configMapRef:
      name: env
  port: 5000
  targetPort: 5000
  workerName: redash-workers
  workerResources:
    limits:
      cpu: 20m
    requests:
      cpu: 10m

postgresVolume:
  name: redash-postgres-data
  mountPathForPostgres: /var/lib/postgresql/data
  volumeMounts:
    - name: redash-postgres-data
      readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: redash-postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

redisVolume:
  name: redash-redis-data
  mountPathForRedis: /data
  volumeMounts:
    - name: redash-redis-data
      readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: redash-redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi